baseURL: "http://example.org/"
languageCode: "en-us"
title: "Association Communautaire Cardinal Creek Community Association"
theme: "ananke"

DefaultContentLanguage: en
copyright: Association Communautaire Cardinal Creek Community Association
languages:
  en:
    title: Cardinal Creek Community Association
    weight: 1
  fr:
    title: Association Communautaire Cardinal Creek
    weight: 2

params:
  navigation:
    help: Help
  permalinks: /:year/:month/:title/
